 baseURL = "https://rhksdn1234.github.io/"
languageCode = "ko-kr"
title = "rhksdn1234 blog"
theme = "PaperMod"         
[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 20
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 30
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 40

[params.profileMode]
  enabled = true
  title = "Tech Blog"
  subtitle = "IT Engineer @ gwanwoo"
  imageUrl = "https://github.com/rhksdn1234.png"
  imageWidth = 150
  imageHeight = 150

  [[params.profileMode.buttons]]
    name = "Archive"
    url = "/archive/"
  [[params.profileMode.buttons]]
    name = "Github"
    url = "https://github.com/rhksdn1234"
